### ISSUE TITLE
To-do list 2020-12-11

### ISSUE THREAD

**Issue by nicewook** [nicewook/wiegandReader#1]
### Arduino part
- [ ] read wiegand data
  - [ ] get palse, width interval - 40us/2000us, 100us/1000us
  - [ ] get total bits, raw data
- [ ] convert it to byte array

### Golang part
- [ ] search and select port
  - [ ] reference package: https://github.com/jacobsa/go-serial
- [ ] json unmarshal and parsing wiegand
  - [ ] total bits, format, card id, facility code, raw wiegand data, parity check, parity bit, etc
- [ ] integrate to icli.exe
